# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/xilinxproject/EE354_Final_Project/tictactoe.srcs/sources_1/ip/blk_mem_gen_tie/blk_mem_gen_tie.xci
# IP: The module: 'blk_mem_gen_tie' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/xilinxproject/EE354_Final_Project/tictactoe.gen/sources_1/ip/blk_mem_gen_tie/blk_mem_gen_tie_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_tie'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/xilinxproject/EE354_Final_Project/tictactoe.srcs/sources_1/ip/blk_mem_gen_tie/blk_mem_gen_tie.xci
# IP: The module: 'blk_mem_gen_tie' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/xilinxproject/EE354_Final_Project/tictactoe.gen/sources_1/ip/blk_mem_gen_tie/blk_mem_gen_tie_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_tie'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
