# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Haily.SKUNKWORK/Downloads/EE354_Final_Project/tictactoe.srcs/sources_1/ip/blk_mem_gen_red/blk_mem_gen_red.xci
# IP: The module: 'blk_mem_gen_red' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Haily.SKUNKWORK/Downloads/EE354_Final_Project/tictactoe.gen/sources_1/ip/blk_mem_gen_red/blk_mem_gen_red_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_red'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Haily.SKUNKWORK/Downloads/EE354_Final_Project/tictactoe.srcs/sources_1/ip/blk_mem_gen_red/blk_mem_gen_red.xci
# IP: The module: 'blk_mem_gen_red' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Haily.SKUNKWORK/Downloads/EE354_Final_Project/tictactoe.gen/sources_1/ip/blk_mem_gen_red/blk_mem_gen_red_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_red'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
