from PIL import Image
import argparse
import os
import datetime # To add a timestamp comment

# --- Configuration ---
# Target bit depth per color channel (for Nexys A7 VGA R4G4B4)
BITS_PER_CHANNEL = 4
TARGET_RADIX = 16 # Output format: 16 for Hex, 10 for Decimal, 2 for Binary

# Calculate the bit shift needed to reduce from 8-bit to target bits
BIT_SHIFT = 8 - BITS_PER_CHANNEL

# Calculate the total number of bits per pixel
TOTAL_BITS = BITS_PER_CHANNEL * 3

# Calculate the number of hex digits needed (adjust if not using HEX)
# For Hex (radix 16): 1 hex digit = 4 bits
HEX_DIGITS = (TOTAL_BITS + 3) // 4

# How many values per line in the COE file for readability
VALUES_PER_LINE = 16
# --- End Configuration ---

def image_to_coe(input_image_path, output_coe_path, target_width=None, target_height=None):
    """
    Converts an image file to a Xilinx COE (.coe) file suitable for BRAM/ROM initialization.

    Args:
        input_image_path (str): Path to the input image file.
        output_coe_path (str): Path to the output COE file (.coe).
        target_width (int, optional): Desired width. Resizes if provided. Defaults to None.
        target_height (int, optional): Desired height. Resizes if provided. Defaults to None.
    """
    try:
        # Open the image
        img = Image.open(input_image_path)
        print(f"Opened image: {input_image_path}")

        # --- Optional Resizing ---
        original_width, original_height = img.size
        if target_width and target_height:
            print(f"Resizing from {original_width}x{original_height} to {target_width}x{target_height}")
            img = img.resize((target_width, target_height), Image.Resampling.LANCZOS)
        else:
            target_width, target_height = original_width, original_height
            print(f"Using original image size: {target_width}x{target_height}")

        # --- Convert to RGB if necessary ---
        if img.mode != 'RGB':
            print(f"Converting image mode from {img.mode} to RGB")
            img = img.convert('RGB')

        # --- Process Pixels and store values ---
        print(f"Processing pixels...")
        pixel_values = []
        for y in range(target_height):
            for x in range(target_width):
                # Get the 8-bit RGB values (0-255)
                r8, g8, b8 = img.getpixel((x, y))

                # Reduce color depth by right-shifting
                r_reduced = r8 >> BIT_SHIFT
                g_reduced = g8 >> BIT_SHIFT
                b_reduced = b8 >> BIT_SHIFT

                # Combine the reduced bits into a single integer value
                combined_value = (r_reduced << (BITS_PER_CHANNEL * 2)) | \
                                 (g_reduced << BITS_PER_CHANNEL)      | \
                                 b_reduced
                pixel_values.append(combined_value)

        print(f"Processed {len(pixel_values)} pixels.")

        # --- Write COE File ---
        print(f"Writing COE file to {output_coe_path}...")
        with open(output_coe_path, 'w') as f_out:
            # Write COE Header
            f_out.write(f"; COE File generated by Python script\n")
            f_out.write(f"; Source Image: {os.path.basename(input_image_path)}\n")
            f_out.write(f"; Dimensions: {target_width}x{target_height}\n")
            f_out.write(f"; Bit Depth: R{BITS_PER_CHANNEL}G{BITS_PER_CHANNEL}B{BITS_PER_CHANNEL} ({TOTAL_BITS}-bit total)\n")
            f_out.write(f"; Generated on: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f_out.write(f"MEMORY_INITIALIZATION_RADIX={TARGET_RADIX};\n")
            f_out.write("MEMORY_INITIALIZATION_VECTOR=\n")

            # Write Data Vector
            num_values = len(pixel_values)
            for i, value in enumerate(pixel_values):
                # Format value based on radix (currently only hex implemented well)
                if TARGET_RADIX == 16:
                     # Format as hexadecimal string with leading zeros
                    format_string = f"{{:0{HEX_DIGITS}X}}" # e.g., "{:03X}" for 12 bits
                    formatted_value = format_string.format(value)
                # Add cases here for radix 10 or 2 if needed
                else:
                    formatted_value = str(value) # Default to string for other radices

                f_out.write(formatted_value)

                # Check if it's the last value
                if i == num_values - 1:
                    f_out.write(";\n") # End with semicolon
                else:
                    f_out.write(",") # Follow with comma
                    # Add newline for readability
                    if (i + 1) % VALUES_PER_LINE == 0:
                        f_out.write("\n")
                    else:
                        f_out.write(" ") # Add space after comma if not breaking line

        print(f"COE file saved successfully: {output_coe_path}")

    except FileNotFoundError:
        print(f"Error: Input image file not found at {input_image_path}")
    except Exception as e:
        print(f"An error occurred: {e}")

# --- Command Line Argument Parsing ---
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Convert image to Xilinx COE format for Vivado BRAM/ROM initialization (R4G4B4 default).")
    parser.add_argument("input_image", help="Path to the input image file (e.g., image.png)")
    parser.add_argument("output_coe", help="Path for the output COE file (e.g., image_data.coe)")
    parser.add_argument("-W", "--width", type=int, help="Target width to resize image to (optional)")
    parser.add_argument("-H", "--height", type=int, help="Target height to resize image to (optional)")

    args = parser.parse_args()

    # Basic validation for resize arguments
    if (args.width and not args.height) or (not args.width and args.height):
        parser.error("If resizing, both --width and --height must be provided.")
    elif args.width and args.height and (args.width <= 0 or args.height <= 0):
         parser.error("--width and --height must be positive integers.")

    image_to_coe(args.input_image, args.output_coe, args.width, args.height)